### ISSUE TITLE
update / add info about libobjects server and general deploy workflow

### ISSUE THREAD

**Issue by evanwill** [uidaholib/digital-collections-docs#8]
who to contact, etc. i.e. the full DC team does not have access to libobjects. people should prep objects and then transfer them to the digital projects manager or other CDIL staff. then CDIL creates derivatives and adds to the libobjects server. (maybe use the "collection update form" to communicate when ready?)

similarly, DC team does not have access to the web server for final deploy. then contact the digital projects manager via the update form to trigger CDIL to deploy or rebuild a collection.

**Comment by aweymo-ui** [comment]
Draft created: https://github.com/uidaholib/digital-collections-docs/tree/aw_08082024_dc_docs_revision
